---
title: "Homework 5"
author: "Adyan Rahman"
date: "`r Sys.Date()`"
output: pdf_document
---

Problem 1

a
```{r}
# The probability of not finding a defective bulb in the first 5 trials and 
#finding one on the 6th trial:

#P(defective on 6th trial) = (1 - p)^5 
#P(defective on 6th trial) = (1 - 1/25)^5 * 1/25
#P(defective on 6th trial) = (24/25)^5 * 1/25
#P(defective on 6th trial) = 0.018

```

b
```{r}
#P(at least 4 trials) = 1 - (1 - p)^3
#P(at least 4 trials) = 1 - (1 - 1/25)^3 = 0.007
```

c
```{r}
#P(at most 10 trials) = 1 - (1 - p)^10
#P(at most 10 trials) = 1 - (1 - 1/25)^10 = 0.118
```


Problem 2
```{r}
# Set seed for reproducibility
set.seed(20220707)

# Simulate rolling 5 fair six-sided dice 10,000 times
rolls <- replicate(10000, sum(sample(1:6, 5, replace = TRUE) == 1))

# Plot histogram
library(ggplot2)
ggplot(data = data.frame(rolls), aes(x = rolls)) +
  geom_histogram(binwidth = 1, fill = "skyblue", color = "black") +
  labs(x = "Number of ones rolled", y = "Frequency", title = "Histogram of Number of Ones Rolled") +
  theme_minimal()

# Calculate sample mean and sample variance
sample_mean <- mean(rolls)
sample_variance <- var(rolls)

# Print sample mean and sample variance rounded to 3 decimal places
print(paste("Sample mean:", round(sample_mean, 3)))
print(paste("Sample variance:", round(sample_variance, 3)))

```
Problem 3
```{r}
# Average rate of cars passing per hour
lambda <- 180

# Convert average rate to rate per minute
lambda_minute <- lambda / 60

# Calculate the probability of congestion (more than 5 cars passing in any one minute) using the Poisson distribution
probability_congestion <- 1 - ppois(5, lambda_minute)

# Round the probability to 3 decimal places
probability_congestion <- round(probability_congestion, 3)

# Print the probability
print(paste("Probability of congestion:", probability_congestion))

# Generate x values (number of cars passing in any one minute)
x <- 0:10

# Calculate the corresponding probabilities using the Poisson distribution
probabilities <- dpois(x, lambda_minute)

# Plot bar chart
library(ggplot2)
ggplot(data = data.frame(x = x, probabilities = probabilities), aes(x = x, y = probabilities)) +
  geom_bar(stat = "identity", fill = "skyblue", color = "black") +
  labs(x = "Number of cars passing in one minute", y = "Probability", title = "Probability of Observation of Cars Passing in One Minute") +
  theme_minimal()

```

Problem 4
```{r}
#Probability of scoring 585 or less: Z = (585 - 500)/100 = 0.85
# Z = 0.85 corresponds to 0.802

#ZLower q = qnorm(0.25,0,1) = -0.675
#ZMedium = qnorm(0.50,0,1) = 0
#ZUpper = qnorm(0.75,0,1) = 0.675
```

Problem 5
```{r}
#P(Red)=0.05 (probability of the cab being red)
#P(Green)=0.95 (probability of the cab being green)
#P(Red|Red)=0.8 (probability of the witness saying the cab was red if it was red)
#P(Green|Green)=0.8 (probability of the witness saying the cab was green if green)

#P(Red|Red) = (P(Red|Red)* P(Red)) / P(Red) = 0.8
```










